public enum Value {
	MAIN_MENU, NEW_MENU, LOAD_MENU, SCORE_MENU, GAME, NEXT_TURN, 
	GAME_OVER, COMPUTER_TURN, HUMAN_TURN, NEW_GAME, DEFAULT,
	NORMAL, SPEED_MODE, TIMER, EASY_AI, HARD_AI,
	LOAD_GAME, EXIT, TWO_PLAYERS, PLAYER_EASY, AI_TURN, HUMAN, AI,
	EASY_EASY, BACK, SCORE, PLAYER_PLAYER, PLAYER_AI, AI_AI, PLAYER_TURN,
	ORANGE, PINK, BLUE, PURPLE, YELLOW, RED, GREEN, BROWN;
}