public enum Value {
	MAIN_MENU, NEW_MENU, LOAD_MENU, SCORE_MENU, GAME, NEXT_TURN, 
	GAME_OVER, COMPUTER_TURN, HUMAN_TURN, NEW_GAME, 
	LOAD_GAME, EXIT, TWO_PLAYERS, PLAYER_EASY, AI_TURN, HUMAN,
	EASY_EASY, BACK, SCORE, PLAYER_PLAYER, PLAYER_AI, AI_AI, PLAYER_TURN;
}