public enum Value {
	MAIN_MENU, NEW_MENU, LOAD_MENU, SCORE_MENU, GAME, NEXT_TURN, TIME_UP,
	GAME_OVER, COMPUTER_TURN, HUMAN_TURN, NEW_GAME, DEFAULT, READY,
	NORMAL, SPEED_MODE, TIMER, EASY_AI, HARD_AI, BEGINNER_AI, RESUME_GAME, HOVER, ACTION,
	LOAD_GAME, EXIT, TWO_PLAYERS, PLAYER_EASY, AI_TURN, HUMAN, AI, BOTTOM, TOP, TIMER_HIDE,
	EASY_EASY, BACK, SCORE, PLAYER_PLAYER, PLAYER_AI, AI_AI, PLAYER_TURN, TIMER_RESET,
	ORANGE, PINK, BLUE, PURPLE, YELLOW, RED, GREEN, BROWN, DOUBLE_DEADLOCK;
}